// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;

namespace SigningServer.Android.Com.Android.Apksig.Apk
{
    [Suite.SuiteClasses({typeof(SigningServer.Android.Com.Android.Apksig.Apk.ApkUtilsTest)})]
    public class AllTests: SigningServer.Android.TestBase
    {
    }
    
}
