// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

/*
 * Copyright (C) 2022 Daniel Kuschny (C# port)
 * Copyright (C) 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;

namespace SigningServer.Android.Com.Android.Apksig.Internal.Apk.V2
{
    /// <summary>
    /// Constants used by the V2 Signature Scheme signing and verification.
    /// </summary>
    public class V2SchemeConstants
    {
        internal V2SchemeConstants()
        {
        }
        
        public static readonly int APK_SIGNATURE_SCHEME_V2_BLOCK_ID = 0x7109871a;
        
        public const int STRIPPING_PROTECTION_ATTR_ID = unchecked((int)0xbeeff00d);
        
    }
    
}
