// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

/*
 * Copyright (C) 2022 Daniel Kuschny (C# port)
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;

namespace SigningServer.Android.Com.Android.Apksig.Internal.Asn1
{
    [System.AttributeUsage(System.AttributeTargets.Field)]
    public class Asn1Field: System.Attribute
    {
        /// <summary>
        /// Index used to order fields in a container. Required for fields of SEQUENCE containers.
        /// </summary>
        public int Index
        {
            get;
            set;
        }
         = 0;
        
        public SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1TagClass Cls
        {
            get;
            set;
        }
         = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1TagClass.AUTOMATIC;
        
        public SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type Type
        {
            get;
            set;
        }
        
        /// <summary>
        /// Tagging mode. Default: NORMAL.
        /// </summary>
        public SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Tagging Tagging
        {
            get;
            set;
        }
         = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Tagging.NORMAL;
        
        /// <summary>
        /// Tag number. Required when IMPLICIT and EXPLICIT tagging mode is used.
        /// </summary>
        public int TagNumber
        {
            get;
            set;
        }
         = -1;
        
        /// <summary>
        /// {@code true} if this field is optional. Ignored for fields of CHOICE containers.
        /// </summary>
        public bool Optional
        {
            get;
            set;
        }
         = false;
        
        /// <summary>
        /// Type of elements. Used only for SET_OF or SEQUENCE_OF.
        /// </summary>
        public SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type ElementType
        {
            get;
            set;
        }
         = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.ANY;
        
    }
    
}
