// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;

namespace SigningServer.Android.Com.Android.Apksig.Internal.Util
{
    public abstract class ByteBufferSinkTestBase: SigningServer.Android.Com.Android.Apksig.Util.DataSinkTestBase<Com.Android.Apksig.Internal.Util.ByteBufferSink>
    {
        internal static readonly int START_POS = 100;
        
        protected abstract SigningServer.Android.IO.ByteBuffer CreateBuffer(int size);
        
        protected override SigningServer.Android.Com.Android.Apksig.Util.DataSinkTestBase.CloseableWithDataSink<Com.Android.Apksig.Internal.Util.ByteBufferSink> CreateDataSink()
        {
            SigningServer.Android.IO.ByteBuffer buf = CreateBuffer(1024);
            buf.Position(SigningServer.Android.Com.Android.Apksig.Internal.Util.ByteBufferSinkTestBase.START_POS);
            buf.Limit(buf.Capacity() - 300);
            return SigningServer.Android.Com.Android.Apksig.Util.DataSinkTestBase.CloseableWithDataSink.Of<Com.Android.Apksig.Internal.Util.ByteBufferSink>(new Com.Android.Apksig.Internal.Util.ByteBufferSink(buf));
        }
        
        protected override SigningServer.Android.IO.ByteBuffer GetContents(Com.Android.Apksig.Internal.Util.ByteBufferSink dataSink)
        {
            SigningServer.Android.IO.ByteBuffer buf = dataSink.GetBuffer();
            int oldPos = buf.Position();
            int oldLimit = buf.Limit();
            try
            {
                buf.Position(SigningServer.Android.Com.Android.Apksig.Internal.Util.ByteBufferSinkTestBase.START_POS);
                buf.Limit(oldPos);
                return buf.Slice();
            }
            finally
            {
                buf.Limit(oldLimit);
                buf.Position(oldPos);
            }
        }
        
    }
    
}
