// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;

namespace SigningServer.Android.Com.Android.Apksig.Internal.X509
{
    /// <summary>
    /// {@code RelativeDistinguishedName} as specified in RFC 5280.
    /// </summary>
    [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Class(Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.UNENCODED_CONTAINER)]
    public class RelativeDistinguishedName
    {
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Index = 0, Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.SET_OF)]
        public SigningServer.Android.Collections.List<SigningServer.Android.Com.Android.Apksig.Internal.X509.AttributeTypeAndValue> attributes;
        
    }
    
}
