// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;

namespace SigningServer.Android.Com.Android.Apksig.Internal.X509
{
    /// <summary>
    /// To Be Signed Certificate as specified in RFC 5280.
    /// </summary>
    [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Class(Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.SEQUENCE)]
    public class TBSCertificate
    {
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Index = 0, Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.INTEGER, Tagging = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Tagging.EXPLICIT, TagNumber = 0)]
        public int version;
        
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Index = 1, Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.INTEGER)]
        public SigningServer.Android.Math.BigInteger serialNumber;
        
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Index = 2, Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.SEQUENCE)]
        public SigningServer.Android.Com.Android.Apksig.Internal.Pkcs7.AlgorithmIdentifier signatureAlgorithm;
        
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Index = 3, Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.CHOICE)]
        public SigningServer.Android.Com.Android.Apksig.Internal.X509.Name issuer;
        
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Index = 4, Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.SEQUENCE)]
        public SigningServer.Android.Com.Android.Apksig.Internal.X509.Validity validity;
        
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Index = 5, Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.CHOICE)]
        public SigningServer.Android.Com.Android.Apksig.Internal.X509.Name subject;
        
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Index = 6, Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.SEQUENCE)]
        public SigningServer.Android.Com.Android.Apksig.Internal.X509.SubjectPublicKeyInfo subjectPublicKeyInfo;
        
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Index = 7, Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.BIT_STRING, Tagging = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Tagging.IMPLICIT, Optional = true, TagNumber = 1)]
        public SigningServer.Android.IO.ByteBuffer issuerUniqueID;
        
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Index = 8, Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.BIT_STRING, Tagging = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Tagging.IMPLICIT, Optional = true, TagNumber = 2)]
        public SigningServer.Android.IO.ByteBuffer subjectUniqueID;
        
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Index = 9, Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.SEQUENCE_OF, Tagging = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Tagging.EXPLICIT, Optional = true, TagNumber = 3)]
        public SigningServer.Android.Collections.List<SigningServer.Android.Com.Android.Apksig.Internal.X509.Extension> extensions;
        
    }
    
}
