// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;

namespace SigningServer.Android.Com.Android.Apksig.Internal.X509
{
    /// <summary>
    /// {@code Time} as specified in RFC 5280.
    /// </summary>
    [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Class(Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.CHOICE)]
    public class Time
    {
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.UTC_TIME)]
        public string utcTime;
        
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.GENERALIZED_TIME)]
        public string generalizedTime;
        
    }
    
}
