// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;

namespace SigningServer.Android.Com.Android.Apksig.Internal.Util
{
    public class ByteBufferUtils
    {
        internal ByteBufferUtils()
        {
        }
        
        /// <summary>
        /// Returns the remaining data of the provided buffer as a new byte array and advances the
        /// position of the buffer to the buffer's limit.
        /// </summary>
        public static sbyte[] ToByteArray(SigningServer.Android.IO.ByteBuffer buf)
        {
            sbyte[] result = new sbyte[buf.Remaining()];
            buf.Get(result);
            return result;
        }
        
    }
    
}
