// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;
using SigningServer.Android.Security.Cert;

namespace SigningServer.Android.Com.Android.Apksig.Internal.Util
{
    /// <summary>
    /// {@link X509Certificate} which delegates all method invocations to the provided delegate
    /// {@code X509Certificate}.
    /// </summary>
    public class DelegatingX509Certificate: SigningServer.Android.Security.Cert.X509Certificate
    {
        internal static readonly long serialVersionUID = 1L;
        
        internal readonly SigningServer.Android.Security.Cert.X509Certificate mDelegate;
        
        public DelegatingX509Certificate(SigningServer.Android.Security.Cert.X509Certificate @delegate)
        {
            this.mDelegate = @delegate;
        }
        
        public override bool HasUnsupportedCriticalExtension()
        {
            return mDelegate.HasUnsupportedCriticalExtension();
        }
        
        public override SigningServer.Android.Math.BigInteger GetSerialNumber()
        {
            return mDelegate.GetSerialNumber();
        }
        
        public override SigningServer.Android.Security.Principal GetIssuerDN()
        {
            return mDelegate.GetIssuerDN();
        }
        
        public override SigningServer.Android.Security.Principal GetSubjectDN()
        {
            return mDelegate.GetSubjectDN();
        }
        
        public override bool[] GetKeyUsage()
        {
            return mDelegate.GetKeyUsage();
        }
        
        public override  byte[] GetEncoded()
        {
            return mDelegate.GetEncoded();
        }
        
        public override string ToString()
        {
            return mDelegate.ToString();
        }
        
        public override SigningServer.Android.Security.PublicKey GetPublicKey()
        {
            return mDelegate.GetPublicKey();
        }
        
        public override X500Principal GetIssuerX500Principal()
        {
            return mDelegate.GetIssuerX500Principal();
        }
    }
}
