// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;

namespace SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Ber
{
    public class InputStreamBerDataValueReaderTest: SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Ber.BerDataValueReaderTestBase
    {
        protected override Com.Android.Apksig.Internal.Asn1.Ber.InputStreamBerDataValueReader CreateReader(sbyte[] input)
        {
            return new Com.Android.Apksig.Internal.Asn1.Ber.InputStreamBerDataValueReader(new SigningServer.Android.IO.ByteArrayInputStream(input));
        }
        
        [Test(Expected = typeof(System.NullReferenceException))]
        public virtual void TestConstructWithNullByteBuffer()
        {
            new Com.Android.Apksig.Internal.Asn1.Ber.InputStreamBerDataValueReader(null);
        }
        
    }
    
}
