// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;

namespace SigningServer.Android.Com.Android.Apksig.Internal.Asn1
{
    /// <summary>
    /// Opaque holder of encoded ASN.1 stuff.
    /// </summary>
    public class Asn1OpaqueObject
    {
        internal readonly SigningServer.Android.IO.ByteBuffer mEncoded;
        
        public Asn1OpaqueObject(SigningServer.Android.IO.ByteBuffer encoded)
        {
            mEncoded = encoded.Slice();
        }
        
        public Asn1OpaqueObject(sbyte[] encoded)
        {
            mEncoded = SigningServer.Android.IO.ByteBuffer.Wrap(encoded);
        }
        
        public virtual SigningServer.Android.IO.ByteBuffer GetEncoded()
        {
            return mEncoded.Slice();
        }
        
    }
    
}
