// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;

namespace SigningServer.Android.Com.Android.Apksig.Internal.Asn1
{
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Interface)]
    public class Asn1Class: System.Attribute
    {
        public SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type Type
        {
            get;
            set;
        }
        
    }
    
}
