// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;

namespace SigningServer.Android.Com.Android.Apksig.Internal.Pkcs7
{
    /// <summary>
    /// PKCS #7 {@code IssuerAndSerialNumber} as specified in RFC 5652.
    /// </summary>
    [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Class(Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.SEQUENCE)]
    public class IssuerAndSerialNumber
    {
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Index = 0, Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.ANY)]
        public SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1OpaqueObject issuer;
        
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Index = 1, Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.INTEGER)]
        public SigningServer.Android.Math.BigInteger certificateSerialNumber;
        
        public IssuerAndSerialNumber()
        {
        }
        
        public IssuerAndSerialNumber(SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1OpaqueObject issuer, SigningServer.Android.Math.BigInteger certificateSerialNumber)
        {
            this.issuer = issuer;
            this.certificateSerialNumber = certificateSerialNumber;
        }
        
    }
    
}
