// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;

namespace SigningServer.Android.Com.Android.Apksig.Internal.Pkcs7
{
    /// <summary>
    /// PKCS #7 {@code SignerIdentifier} as specified in RFC 5652.
    /// </summary>
    [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Class(Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.CHOICE)]
    public class SignerIdentifier
    {
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.SEQUENCE)]
        public SigningServer.Android.Com.Android.Apksig.Internal.Pkcs7.IssuerAndSerialNumber issuerAndSerialNumber;
        
        [SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Field(Type = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Type.OCTET_STRING, Tagging = SigningServer.Android.Com.Android.Apksig.Internal.Asn1.Asn1Tagging.IMPLICIT, TagNumber = 0)]
        public SigningServer.Android.IO.ByteBuffer subjectKeyIdentifier;
        
        public SignerIdentifier()
        {
        }
        
        public SignerIdentifier(SigningServer.Android.Com.Android.Apksig.Internal.Pkcs7.IssuerAndSerialNumber issuerAndSerialNumber)
        {
            this.issuerAndSerialNumber = issuerAndSerialNumber;
        }
        
    }
    
}
