// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;

namespace SigningServer.Android.Com.Android.Apksig.Internal.Apk.V3
{
    /// <summary>
    /// Constants used by the V3 Signature Scheme signing and verification.
    /// </summary>
    public class V3SchemeConstants
    {
        internal V3SchemeConstants()
        {
        }
        
        public static readonly int APK_SIGNATURE_SCHEME_V3_BLOCK_ID = 0xf05368c0;
        
        public static readonly int PROOF_OF_ROTATION_ATTR_ID = 0x3ba06f8c;
        
    }
    
}
