// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;

namespace SigningServer.Android.Com.Android.Apksig.Util
{
    /// <summary>
    /// {@link DataSink} which exposes all data consumed so far as a {@link DataSource}. This abstraction
    /// offers append-only write access and random read access.
    /// </summary>
    public interface ReadableDataSink: SigningServer.Android.Com.Android.Apksig.Util.DataSink, SigningServer.Android.Com.Android.Apksig.Util.DataSource
    {
    }
    
}
