// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;
using SigningServer.Android.Core;

namespace SigningServer.Android.Com.Android.Apksig.Util
{
    public interface RunnablesProvider
    {
        public SigningServer.Android.Core.Runnable CreateRunnable();
        
    }

    public class DelegateRunnablesProvider : RunnablesProvider
    {
        private readonly Func<Runnable> mCreateRunnable;

        public DelegateRunnablesProvider(Func<SigningServer.Android.Core.Runnable> createRunnable)
        {
            mCreateRunnable = createRunnable;
        }
        public Runnable CreateRunnable()
        {
            return mCreateRunnable();
        }
    }
    
}
