name: Prerelease
on: 
  workflow_dispatch:
    inputs:
      build:
        required: true
        description: Pre Release Build Number
        type: string
jobs:
  build:
    name: Create Prerelease
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      - uses: microsoft/setup-msbuild@v1
      - run: dotnet build SigningServer.sln --configuration=Release -p:BuildNumber=${{ inputs.build }} -p:VersionSuffix=alpha.${{ inputs.build }}
      - run: dotnet publish SigningServer.sln --configuration=${{ matrix.configuration }} -p:BuildNumber=${{ github.run_number }} -p:VersionSuffix=alpha.${{ github.run_number }}
      - run: dotnet pack SigningServer.sln --configuration=Release -p:BuildNumber=${{ inputs.build }} -p:VersionSuffix=alpha.${{ inputs.build }}
      - name: Archive Server Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: SigningServer.Server
          path: |
            SigningServer.Server/bin/${{ matrix.configuration }}/*/publish/**/*.*
      - name: Archive Client Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: SigningServer.Client
          path: |
            SigningServer.Client/bin/${{ matrix.configuration }}/*/publish/**/*.*
      - name: Archive StandaloneClient Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: SigningServer.StandaloneClient ${{ matrix.configuration }}
          path: |
            SigningServer.StandaloneClient/bin/${{ matrix.configuration }}/*/publish/**/*.*
      - name: Archive Client .net Tool
        uses: actions/upload-artifact@v2
        with:
          name: SigningServer.Client.Tool
          path: |
            SigningServer.Client/bin/${{ matrix.configuration }}/*.nupkg
      - name: Publish NuGet (Client) 
        run: dotnet nuget push SigningServer.Client\bin\Release\*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
      - name: Publish NuGet (Standalone Client)
        run: dotnet nuget push SigningServer.StandaloneClient\bin\Release\*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
