name: Release
on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    if: ${{ !contains(github.ref_name, '-') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9'
      - run: dotnet build SigningServer.sln --configuration=Release
      - run: dotnet publish SigningServer.sln --configuration=Release
      - run: dotnet pack SigningServer.sln --configuration=Release

      - name: Archive Server Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SigningServer.Server
          path: |
            SigningServer.Server/bin/Release/*/publish/**/*.*
      - name: Archive Client Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SigningServer.Client
          path: |
            SigningServer.Client/bin/Release/*/publish/**/*.*
      - name: Archive StandaloneClient Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SigningServer.StandaloneClient
          path: |
            SigningServer.StandaloneClient/bin/Release/*/publish/**/*.*
      - name: Archive Client .net Tool
        uses: actions/upload-artifact@v4
        with:
          name: SigningServer.Client.Tool
          path: |
            SigningServer.Client/bin/Release/*.nupkg
      - name: Archive SelfContainedClient Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SigningServer.SelfContainedClient
          path: |
            SigningServer.SelfContainedClient/bin/Release/*.nupkg
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            Changes in this Release
            - TODO
          draft: true
          prerelease: false
      - name: Publish NuGet (Client)
        run: dotnet nuget push SigningServer.Client\bin\Release\*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
      - name: Publish NuGet (Standalone Client)
        run: dotnet nuget push SigningServer.StandaloneClient\bin\Release\*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
      - name: Publish NuGet (SelfContained Client)
        run: dotnet nuget push SigningServer.SelfContainedClient\bin\Release\*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json