// <auto-generated>
// This code was auto-generated.
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>

using System;

namespace SigningServer.Android.Com.Android.Apksig.Internal.Apk.V2
{
    /// <summary>
    /// Constants used by the V2 Signature Scheme signing and verification.
    /// </summary>
    public class V2SchemeConstants
    {
        internal V2SchemeConstants()
        {
        }
        
        public static readonly int APK_SIGNATURE_SCHEME_V2_BLOCK_ID = 0x7109871a;
        
        public const int STRIPPING_PROTECTION_ATTR_ID = 0xbeeff00d;
        
    }
    
}
